

```{r}
rm(list = ls())
library(data.table)

#info = read.csv("SraRunInfo.csv")
#sort(table(info$BioProject), decreasing = T)

zizania_palustris = fread("SraRunInfo_zizania_palustris_2023-03-10.csv.gz", data.table = F)
sort(table(zizania_palustris$BioProject), decreasing = T)

vanilla_planifolia = fread("SraRunInfo_vanilla_planifolia_2023-03-10.csv.gz", data.table = F)
sort(table(vanilla_planifolia$BioProject), decreasing = T)

trifolium_pratense = fread("SraRunInfo_trifolium_pratense_2023-03-09.csv.gz", data.table = F)
sort(table(trifolium_pratense$BioProject), decreasing = T)

raphanus_sativus = fread("SraRunInfo_raphanus_sativus_2023-02-18.csv.gz", data.table = F)
sort(table(raphanus_sativus$BioProject), decreasing = T)

solanum_melongena = fread("SraRunInfo_solanum_melongena_2023-02-14.csv.gz", data.table = F)
sort(table(solanum_melongena$BioProject), decreasing = T)

solanum_pimpinellifolium = fread("SraRunInfo_solanum_pimpinellifolium_2023-02-14.csv.gz", data.table = F)
sort(table(solanum_pimpinellifolium$BioProject), decreasing = T)

nicotiana_benthamiana = fread("SraRunInfo_nicotiana_benthamiana_2023-02-14.csv.gz", data.table = F)
sort(table(nicotiana_benthamiana$BioProject), decreasing = T)

nicotiana_tabacum = fread("SraRunInfo_nicotiana_tabacum_2023-02-14.csv.gz", data.table = F)
sort(table(nicotiana_tabacum$BioProject), decreasing = T)

actinidia_chinensis = fread("SraRunInfo_actinidia_chinensis_2023-01-11.csv.gz", data.table = F)
sort(table(actinidia_chinensis$BioProject), decreasing = T)

aegilops_tauschii = fread("SraRunInfo_aegilops_tauschii_2023-01-11.csv.gz", data.table = F)
sort(table(aegilops_tauschii$BioProject), decreasing = T)

arabis_alpina = fread("SraRunInfo_arabis_alpina_2022-12-22.csv.gz", data.table = F)
sort(table(arabis_alpina$BioProject), decreasing = T)

brassica_juncea = fread("SraRunInfo_brassica_juncea_2023-01-11.csv.gz", data.table = F)
sort(table(brassica_juncea$BioProject), decreasing = T)

brassica_napus = fread("SraRunInfo_brassica_napus_2023-01-11.csv.gz", data.table = F)
sort(table(brassica_napus$BioProject), decreasing = T)

camelina_sativa = fread("SraRunInfo_camelina_sativa_2023-01-11.csv.gz", data.table = F)
sort(table(camelina_sativa$BioProject), decreasing = T)

cannabis_sativa = fread("SraRunInfo_cannabis_sativa_2023-01-11.csv.gz", data.table = F)
sort(table(cannabis_sativa$BioProject), decreasing = T)

capsicum_annuum = fread("SraRunInfo_capsicum_annuum_2023-01-12.csv.gz", data.table = F)
sort(table(capsicum_annuum$BioProject), decreasing = T)

coffea_canephora = fread("SraRunInfo_coffea_canephora_2023-01-12.csv.gz", data.table = F)
sort(table(coffea_canephora$BioProject), decreasing = T)

corylus_avellana = fread("SraRunInfo_corylus_avellana_2023-01-12.csv.gz", data.table = F)
sort(table(corylus_avellana$BioProject), decreasing = T)

cucumis_melo = fread("SraRunInfo_cucumis_melo_2023-01-12.csv.gz", data.table = F)
sort(table(cucumis_melo$BioProject), decreasing = T)

digitaria_exilis = fread("SraRunInfo_digitaria_exilis_2023-01-12.csv.gz", data.table = F)
sort(table(digitaria_exilis$BioProject), decreasing = T)

ficus_carica = fread("SraRunInfo_ficus_carica_2023-01-12.csv.gz", data.table = F)
sort(table(ficus_carica$BioProject), decreasing = T)

juglans_regia = fread("SraRunInfo_juglans_regia_2023-01-13.csv.gz", data.table = F)
sort(table(juglans_regia$BioProject), decreasing = T)

lolium_perenne = fread("SraRunInfo_lolium_perenne_2023-01-13.csv.gz", data.table = F)
sort(table(lolium_perenne$BioProject), decreasing = T)

marchantia_polymorpha = fread("SraRunInfo_marchantia_polymorpha_2023-01-13.csv.gz", data.table = F)
sort(table(marchantia_polymorpha$BioProject), decreasing = T)

oryza_brachyantha = fread("SraRunInfo_oryza_brachyantha_2023-01-14.csv.gz", data.table = F)
sort(table(oryza_brachyantha$BioProject), decreasing = T)

oryza_glaberrima = fread("SraRunInfo_oryza_glaberrima_2023-01-14.csv.gz", data.table = F)
sort(table(oryza_glaberrima$BioProject), decreasing = T)

oryza_glumipatula = fread("SraRunInfo_oryza_glumipatula_2023-01-14.csv.gz", data.table = F)
sort(table(oryza_glumipatula$BioProject), decreasing = T)

oryza_longistaminata = fread("SraRunInfo_oryza_longistaminata_2023-01-14.csv.gz", data.table = F)
sort(table(oryza_longistaminata$BioProject), decreasing = T)

oryza_meridionalis = fread("SraRunInfo_oryza_meridionalis_2023-01-14.csv.gz", data.table = F)
sort(table(oryza_meridionalis$BioProject), decreasing = T)

oryza_nivara = fread("SraRunInfo_oryza_nivara_2023-01-14.csv.gz", data.table = F)
sort(table(oryza_nivara$BioProject), decreasing = T)

oryza_punctata = fread("SraRunInfo_oryza_punctata_2023-01-16.csv.gz", data.table = F)
sort(table(oryza_punctata$BioProject), decreasing = T)

oryza_rufipogon = fread("SraRunInfo_oryza_rufipogon_2023-01-16.csv.gz", data.table = F)
sort(table(oryza_rufipogon$BioProject), decreasing = T)

papaver_somniferum = fread("SraRunInfo_papaver_somniferum_2023-01-16.csv.gz", data.table = F)
sort(table(papaver_somniferum$BioProject), decreasing = T)

pisum_sativum = fread("SraRunInfo_pisum_sativum_2023-01-16.csv.gz", data.table = F)
sort(table(pisum_sativum$BioProject), decreasing = T)

pisum_sativum = fread("SraRunInfo_pisum_sativum_2023-01-16.csv.gz", data.table = F)
sort(table(pisum_sativum$BioProject), decreasing = T)

phoenix_dactylifera = fread("SraRunInfo_phoenix_dactylifera_2023-01-30.csv.gz", data.table = F)
sort(table(phoenix_dactylifera$BioProject), decreasing = T)

prunus_dulcis = fread("SraRunInfo_prunus_dulcis_2023-01-16.csv.gz", data.table = F)
sort(table(prunus_dulcis$BioProject), decreasing = T)

quercus_lobata = fread("SraRunInfo_quercus_lobata_2023-01-16.csv.gz", data.table = F)
sort(table(quercus_lobata$BioProject), decreasing = T)

quercus_suber = fread("SraRunInfo_quercus_suber_2023-01-16.csv.gz", data.table = F)
sort(table(quercus_suber$BioProject), decreasing = T)

rosa_chinensis = fread("SraRunInfo_rosa_chinensis_2023-01-16.csv.gz", data.table = F)
sort(table(rosa_chinensis$BioProject), decreasing = T)

sesamum_indicum = fread("SraRunInfo_sesamum_indicum_2023-01-16.csv.gz", data.table = F)
sort(table(sesamum_indicum$BioProject), decreasing = T)

triticum_dicoccoides = fread("SraRunInfo_triticum_dicoccoides_2023-01-16.csv.gz", data.table = F)
sort(table(triticum_dicoccoides$BioProject), decreasing = T)

vigna_radiata = fread("SraRunInfo_vigna_radiata_2023-01-16.csv.gz", data.table = F)
sort(table(vigna_radiata$BioProject), decreasing = T)

vigna_unguiculata = fread("SraRunInfo_vigna_unguiculata_2023-01-16.csv.gz", data.table = F)
sort(table(vigna_unguiculata$BioProject), decreasing = T)

cajanus_cajan = fread("SraRunInfo_cajanus_cajan_2023-02-02.csv.gz", data.table = F)
sort(table(cajanus_cajan$BioProject), decreasing = T)

camellia_sinensis = fread("SraRunInfo_camellia_sinensis_2023-02-02.csv.gz", data.table = F)
sort(table(camellia_sinensis$BioProject), decreasing = T)

camellia_sinensis = fread("SraRunInfo_camellia_sinensis_2023-02-02.csv.gz", data.table = F)
sort(table(camellia_sinensis$BioProject), decreasing = T)

castanea_mollissima = fread("SraRunInfo_castanea_mollissima_2023-02-02.csv.gz", data.table = F)
sort(table(castanea_mollissima$BioProject), decreasing = T)

coffea_arabica = fread("SraRunInfo_coffea_arabica_2023-02-02.csv.gz", data.table = F)
sort(table(coffea_arabica$BioProject), decreasing = T)

cucurbita_moschata = fread("SraRunInfo_cucurbita_moschata_2023-02-02.csv.gz", data.table = F)
sort(table(cucurbita_moschata$BioProject), decreasing = T)

cucurbita_pepo = fread("SraRunInfo_cucurbita_pepo_2023-02-02.csv.gz", data.table = F)
sort(table(cucurbita_pepo$BioProject), decreasing = T)

elaeis_guineensis = fread("SraRunInfo_elaeis_guineensis_2023-02-03.csv.gz", data.table = F)
sort(table(elaeis_guineensis$BioProject), decreasing = T)

eleusine_coracana = fread("SraRunInfo_eleusine_coracana_2023-02-03.csv.gz", data.table = F)
sort(table(eleusine_coracana$BioProject), decreasing = T)

gossypium_arboreum = fread("SraRunInfo_gossypium_arboreum_2023-02-03.csv.gz", data.table = F)
sort(table(gossypium_arboreum$BioProject), decreasing = T)

hevea_brasiliensis = fread("SraRunInfo_hevea_brasiliensis_2023-02-03.csv.gz", data.table = F)
sort(table(hevea_brasiliensis$BioProject), decreasing = T)

jatropha_curcas = fread("SraRunInfo_jatropha_curcas_2023-02-03.csv.gz", data.table = F)
sort(table(jatropha_curcas$BioProject), decreasing = T)

malus_domestica = fread("SraRunInfo_malus_domestica_2023-02-03.csv.gz", data.table = F)
sort(table(malus_domestica$BioProject), decreasing = T)

mangifera_indica = fread("SraRunInfo_mangifera_indica_2023-02-03.csv.gz", data.table = F)
sort(table(mangifera_indica$BioProject), decreasing = T)

momordica_charantia = fread("SraRunInfo_momordica_charantia_2023-02-03.csv.gz", data.table = F)
sort(table(momordica_charantia$BioProject), decreasing = T)

nelumbo_nucifera = fread("SraRunInfo_nelumbo_nucifera_2023-02-03.csv.gz", data.table = F)
sort(table(nelumbo_nucifera$BioProject), decreasing = T)

perilla_frutescens = fread("SraRunInfo_perilla_frutescens_2023-02-03.csv.gz", data.table = F)
sort(table(perilla_frutescens$BioProject), decreasing = T)

populus_deltoides = fread("SraRunInfo_populus_deltoides_2023-02-03.csv.gz", data.table = F)
sort(table(populus_deltoides$BioProject), decreasing = T)

prunus_armeniaca = fread("SraRunInfo_prunus_armeniaca_2023-02-03.csv.gz", data.table = F)
sort(table(prunus_armeniaca$BioProject), decreasing = T)

quercus_robur = fread("SraRunInfo_quercus_robur_2023-02-03.csv.gz", data.table = F)
sort(table(quercus_robur$BioProject), decreasing = T)

thlaspi_arvense = fread("SraRunInfo_thlaspi_arvense_2023-02-03.csv.gz", data.table = F)
sort(table(thlaspi_arvense$BioProject), decreasing = T)

ziziphus_jujuba = fread("SraRunInfo_ziziphus_jujuba_2023-02-03.csv", data.table = F)
sort(table(ziziphus_jujuba$BioProject), decreasing = T)

cgrandiflora = read.csv("SraRunInfo_capsella_grandiflora.csv")
sort(table(cgrandiflora$BioProject), decreasing = T)

bdistachyon = read.csv("SraRunInfo_brachypodium_distachyon_2022-10-05.csv")
sort(table(bdistachyon$BioProject), decreasing = T)

brachypodium_hybridum = fread("SraRunInfo_brachypodium_hybridum_2022-12-22.csv.gz", data.table = F)
sort(table(brachypodium_hybridum$BioProject), decreasing = T)

tintermedium = read.csv("SraRunInfo_thinopyrum_intermedium.csv")
sort(table(tintermedium$BioProject), decreasing = T)

arabidopsis_lyrata = fread("SraRunInfo_arabidopsis_lyrata_2022-10-14.csv.gz", data.table = F, header = T)
sort(table(arabidopsis_lyrata$BioProject), decreasing = T)

arachis_hypogaea = read.csv("SraRunInfo_arachis_hypogaea_2022-10-11.csv")
sort(table(arachis_hypogaea$BioProject), decreasing = T)

brassica_oleracea = read.csv("SraRunInfo_brassica_oleracea_2022-10-11.csv")
sort(table(brassica_oleracea$BioProject), decreasing = T)

brassica_rapa = read.csv("SraRunInfo_brassica_rapa_2022-10-11.csv")
sort(table(brassica_rapa$BioProject), decreasing = T)

capsella_rubella = read.csv("SraRunInfo_capsella_rubella.csv")
sort(table(capsella_rubella$BioProject), decreasing = T)

cicer_arietinum = read.csv("SraRunInfo_cicer_arietinum_2022-10-13.csv")
sort(table(cicer_arietinum$BioProject), decreasing = T)

citrus_sinensis = read.csv("SraRunInfo_citrus_sinensis_2022-10-13.csv")
sort(table(citrus_sinensis$BioProject), decreasing = T)

cucumis_sativus = read.csv("SraRunInfo_cucumis_sativus_2022-10-13.csv")
sort(table(cucumis_sativus$BioProject), decreasing = T)

fragaria_x_ananassa = read.csv("SraRunInfo_fragaria_x_ananassa_2022-10-13.csv")
sort(table(fragaria_x_ananassa$BioProject), decreasing = T)

glycine_max = read.csv("SraRunInfo_glycine_max_2022-12-06.csv")
sort(table(glycine_max$BioProject), decreasing = T)

lactuca_sativa = read.csv("SraRunInfo_lactuca_sativa_2022-10-13.csv")
sort(table(lactuca_sativa$BioProject), decreasing = T)

linum_usitatissimum = fread("SraRunInfo_linum_usitatissimum_2022-10-13.csv.gz", data.table = F)
sort(table(linum_usitatissimum$BioProject), decreasing = T)

lotus_japonicus = read.csv("SraRunInfo_lotus_japonicus_2022-10-13.csv")
sort(table(lotus_japonicus$BioProject), decreasing = T)

manihot_esculenta = read.csv("SraRunInfo_manihot_esculenta_2022-10-13.csv")
sort(table(manihot_esculenta$BioProject), decreasing = T)

medicago_truncatula = read.csv("SraRunInfo_medicago_truncatula_2022-10-13.csv")
sort(table(medicago_truncatula$BioProject), decreasing = T)

miscanthus_sinensis = read.csv("SraRunInfo_miscanthus_sinensis_2022-10-13.csv.gz")
sort(table(miscanthus_sinensis$BioProject), decreasing = T)

musa_acuminata = read.csv("SraRunInfo_musa_acuminata_2022-10-13.csv")
sort(table(musa_acuminata$BioProject), decreasing = T)

olea_europaea = read.csv("SraRunInfo_olea_europaea_2022-10-13.csv")
sort(table(olea_europaea$BioProject), decreasing = T)

panicum_hallii = read.csv("SraRunInfo_panicum_hallii_2022-10-13.csv")
sort(table(panicum_hallii$BioProject), decreasing = T)

panicum_virgatum = read.csv("SraRunInfo_panicum_virgatum_2022-10-13.csv")
sort(table(panicum_virgatum$BioProject), decreasing = T)

populus_trichocarpa = read.csv("SraRunInfo_populus_trichocarpa_2022-10-04.csv")
sort(table(populus_trichocarpa$BioProject), decreasing = T)

prunus_persica = read.csv("SraRunInfo_prunus_persica_2022-10-13.csv")
sort(table(prunus_persica$BioProject), decreasing = T)

salix_purpurea = read.csv("SraRunInfo_salix_purpurea_2022-10-14.csv")
sort(table(salix_purpurea$BioProject), decreasing = T)

secale_cereale = read.csv("SraRunInfo_secale_cereale_2023-01-11.csv.gz")
sort(table(secale_cereale$BioProject), decreasing = T)

setaria_italica = read.csv("SraRunInfo_setaria_italica_2022-10-14.csv")
sort(table(setaria_italica$BioProject), decreasing = T)

setaria_viridis = read.csv("SraRunInfo_setaria_viridis_2022-10-14.csv")
sort(table(setaria_viridis$BioProject), decreasing = T)

solanum_lycopersicum = read.csv("SraRunInfo_solanum_lycopersicum_2022-10-14.csv")
sort(table(solanum_lycopersicum$BioProject), decreasing = T)

solanum_tuberosum = read.csv("SraRunInfo_solanum_tuberosum_2022-10-14.csv")
sort(table(solanum_tuberosum$BioProject), decreasing = T)

sorghum_bicolor = read.csv("SraRunInfo_sorghum_bicolor_2022-10-14.csv")
sort(table(sorghum_bicolor$BioProject), decreasing = T)

triticum_aestivum = fread("SraRunInfo_triticum_aestivum_2022-12-21.csv.gz", data.table = F)
sort(table(triticum_aestivum$BioProject), decreasing = T)

triticum_turgidum = fread("SraRunInfo_triticum_turgidum_2022-10-14.csv.gz", data.table = F)
sort(table(triticum_turgidum$BioProject), decreasing = T)

vitis_vinifera = read.csv("SraRunInfo_vitis_vinifera_2022-10-14.csv")
sort(table(vitis_vinifera$BioProject), decreasing = T)

zostera_marina = fread("SraRunInfo_zostera_marina_2022-10-14.csv.gz", data.table = F)
sort(table(zostera_marina$BioProject), decreasing = T)


```


## Explore genomes in NCBI that aren't in phytozome or ensembl
```{r}

genomeInfo = fread("Genome_info_plants_landplants_excludePartial_2023-01-30.csv.gz", data.table = F)

# Want annotations with CDS to look at 4-fold degenerate sites
genomeInfo = genomeInfo[(genomeInfo$CDS > 0),]

# remove genomes with only plastid sequences
genomeInfo = genomeInfo[( grepl("chromosome", genomeInfo$Replicons) | genomeInfo$Replicons == ""),]

# remove genomes where annotations can't be downloaded via ftp
genomeInfo = genomeInfo[!(genomeInfo$`RefSeq FTP` == "" & genomeInfo$`GenBank FTP` == ""),]

# extract just species names, remove duplicates
genomes = genomeInfo[,1]

# remove varieties and subspecies
genomes = gsub(" subsp\\..*$", "", genomes)
genomes = gsub(" var\\..*$", "", genomes)
genomes = unique(genomes)

# remove hybrids
genomes = genomes[!grepl(" x ", genomes)]

# remove genomes that I've already looked at
alreadySearched = c("Amaranthus hypochondriacus",
"Amaranthus tuberculatus",
"Amborella trichopoda",
"Ananas comosus",
"Aquilegia coerulea",
"Arabidopsis halleri",
"Arabidopsis lyrata",
"Arabidopsis thaliana",
"Arachis hypogaea",
"Asparagus officinalis",
"Beta vulgaris",
"Betula platyphylla",
"Boechera stricta",
"Brachypodium distachyon",
"Brachypodium hybridum",
"Brachypodium stacei",
"Brassica oleracea capitata",
"Brassica rapa",
"Capsella grandiflora",
"Capsella orientalis",
"Capsella rubella",
"Carica papaya",
"Carya illinoinensis",
"Chenopodium quinoa",
"Cicer arietinum",
"Cinnamomum kanehirae",
"Citrullus lanatus",
"Citrus clementina",
"Citrus sinensis",
"Corymbia citriodora",
"Cucumis sativus",
"Daucus carota",
"Dioscorea alata",
"Diphasiastrum complanatum",
"Eucalyptus grandis",
"Eutrema salsugineum",
"Fragaria vesca",
"Fragaria x ananassa",
"Glycine max",
"Glycine soja",
"Gossypium barbadense",
"Gossypium darwinii",
"Gossypium hirsutum",
"Gossypium mustelinum",
"Gossypium raimondii",
"Gossypium tomentosum",
"Helianthus annuus",
"Hordeum vulgare",
"Kalanchoe fedtschenkoi",
"Lactuca sativa",
"Lens culinaris",
"Lens ervoides",
"Linum usitatissimum",
"Liriodendron tulipifera",
"Lotus japonicus",
"Lupinus albus",
"Manihot esculenta",
"Medicago truncatula",
"Mimulus guttatus",
"Miscanthus sinensis",
"Musa acuminata",
"Nymphaea colorata",
"Olea europaea",
"Oropetium thomaeum",
"Oryza sativa",
"Panicum hallii",
"Panicum virgatum",
"Phaseolus acutifolius",
"Phaseolus vulgaris",
"Poncirus trifoliata",
"Populus trichocarpa",
"Prunus persica",
"Ricinus communis",
"Salix purpurea",
"Schrenkiella parvula",
"Setaria italica",
"Setaria viridis",
"Solanum lycopersicum",
"Solanum tuberosum",
"Sorghum bicolor",
"Spinacia oleracea",
"Spirodela polyrhiza",
"Theobroma cacao",
"Thinopyrum intermedium",
"Trifolium pratense",
"Triticum aestivum",
"Triticum turgidum",
"Vaccinium darrowii",
"Vigna unguiculata",
"Vitis vinifera",
"Zea mays",
"Zostera marina",
"Arabis alpina",
"Actinidia chinensis",
"Aegilops tauschii",
"Brassica juncea",
"Brassica napus",
"Secale cereale",
"Camelina sativa",
"Cannabis sativa",
"Capsicum annuum",
"Chara braunii",
"Chlamydomonas reinhardtii",
"Chondrus crispus",
"Coffea canephora",
"Corchorus capsularis",
"Corylus avellana",
"Corymbia citriodora",
"Cucumis melo",
"Cyanidioschyzon merolae",
"Cynara cardunculus",
"Digitaria exilis",
"Dioscorea rotundata",
"Echinochloa crus-galli",
"Eragrostis curvula",
"Eragrostis tef",
"Ficus carica",
"Galdieria sulphuraria",
"Ipomoea triloba",
"Juglans regia",
"Leersia perrieri",
"Lolium perenne",
"Lupinus angustifolius",
"Marchantia polymorpha",
"Nicotiana attenuata",
"Oryza barthii",
"Oryza brachyantha",
"Oryza glaberrima",
"Oryza glumipatula",
"Oryza longistaminata",
"Oryza meridionalis",
"Oryza nivara",
"Oryza punctata",
"Oryza rufipogon",
"Ostreococcus lucimarinus",
"Papaver somniferum",
"Physcomitrium patens",
"Pistacia vera",
"Pisum sativum",
"Prunus avium",
"Prunus dulcis",
"Quercus lobata",
"Quercus suber",
"Rosa chinensis",
"Saccharum spontaneum",
"Selaginella moellendorffii",
"Sesamum indicum",
"Triticum dicoccoides",
"Triticum spelta",
"Triticum urartu",
"Vigna angularis",
"Vigna radiata",
"Vigna unguiculata",
"Picea abies",
"Phoenix dactylifera")

genomes = genomes[!(genomes %in% alreadySearched)]

# sort alphabetically
genomes = sort(genomes)

# remove Oryza sativa
genomes = genomes[!grepl("Oryza sativa", genomes)]

genomes = genomes[(genomes != "Brassica oleracea")]
```