# Purpose: organize sra data from multiple species for input into snakemake workflow

# clear wd and load packages
```{r}
rm(list = ls())

# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("SRAdb")

speciesList = unique(read.csv("../workflow/data/speciesList.csv")$Species)
```

# Manually check top few bioprojects for each species to see if they're WGS data
```{r}

```

# Split SRA run data into single-end and paired end
## Arabidopsis thaliana
```{r}
athalSraRunInfo = read.csv("../workflow/data/SraRunInfo_arabidopsis_thaliana.csv")

# separate paired end and single-end data
# if spot_with_mates == 0 in sra run info, then data is single-end
athalSe = athalSraRunInfo[(athalSraRunInfo$spots_with_mates == 0),"Run"]
athalPe = athalSraRunInfo[(athalSraRunInfo$spots_with_mates != 0), "Run"]

# add assembly name to file
# can subset data here to get toy dataset
athalSe = data.frame(samples = athalSe, genome = "arabidopsis_thaliana")
athalPe = data.frame(samples = athalPe, genome = "arabidopsis_thaliana")

# write single-end and paired-end samples to separate files
write.table(athalSe, file = "../workflow/data/samples_se.tsv", sep = "\t", quote = F, row.names = F)
write.table(athalPe, file = "../workflow/data/samples_pe.tsv", sep = "\t", quote = F, row.names = F)
```